// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB13HP6jf6LjbQezt3cNtuM3Mf25JQXqw',
    appId: '1:898019520872:web:0929acd2e32d94fba026dd',
    messagingSenderId: '898019520872',
    projectId: 'flutter-crud-4b633',
    authDomain: 'flutter-crud-4b633.firebaseapp.com',
    storageBucket: 'flutter-crud-4b633.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHp90MTU0-PExaiqpRKPdJhxpaMLsZ8n0',
    appId: '1:898019520872:android:ab25ee2fdda997d0a026dd',
    messagingSenderId: '898019520872',
    projectId: 'flutter-crud-4b633',
    storageBucket: 'flutter-crud-4b633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmRylPPV4ZnuP3s1ayGkUnl2DB1v200k',
    appId: '1:898019520872:ios:968b5092a8e46491a026dd',
    messagingSenderId: '898019520872',
    projectId: 'flutter-crud-4b633',
    storageBucket: 'flutter-crud-4b633.appspot.com',
    iosClientId: '898019520872-a7nc50t90gsp1f30pdikihls63q7f9k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseweek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmRylPPV4ZnuP3s1ayGkUnl2DB1v200k',
    appId: '1:898019520872:ios:968b5092a8e46491a026dd',
    messagingSenderId: '898019520872',
    projectId: 'flutter-crud-4b633',
    storageBucket: 'flutter-crud-4b633.appspot.com',
    iosClientId: '898019520872-a7nc50t90gsp1f30pdikihls63q7f9k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseweek',
  );
}
